[package]
name = "bleebo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-web = "4"
actix-web-httpauth = "0.8.1"
futures-util = "0.3.30"
